spring:
  application:
    name: aggregator-service
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  cloud:
    function:
      definition: uppercase;aggregate
    stream:
      bindings:
        uppercase-in-0:
          destination: "uppercase.in.v1"
          group: uppercase-consumer-group
          # contentType: application/json
          consumer:
            max-attempts: 3                   # retry delivery attempts
            back-off-initial-interval: 500    # wait time before first retry (ms)
            back-off-max-interval: 10000      # The maximum backoff interval (ms)
            back-off-multiplier: 2.0          # retry delay grows exponentially. 1.0 means fixed retry delay
            default-retryable: false          # should we retry all the exceptions? Default: true
            retryable-exceptions:
              com.example.aggregator.exceptions.BadRequestException: false # do not retry
              com.example.aggregator.exceptions.MissingDataException: false # do not retry
              com.example.aggregator.exceptions.TimeoutException: true #  retry
        uppercase-out-0:
          destination: "uppercase.out.v1"

        aggregate-in-0:
          destination: topic-1,topic-2,topic-3,topic-4
          group: aggregator-consumer-group
          # contentType: application/json
          consumer:
            use-native-decoding: true   # let Kafka Streams handle deserialization
        aggregate-out-0:
          destination: aggregated-topic
          producer:
            use-native-encoding: true   # let Kafka Streams handle serialization
      kafka:
        streams:
          binder:
            brokers: ${KAFKA_BROKERS:localhost:19092}
            autoCreateTopics: true
            minPartitionCount: 1
#            consumer-properties:
#              auto.offset.reset: earliest
#              max.poll.records: 20
            configuration:
              processing.guarantee: exactly_once_v2
              commit.interval.ms: 100
          bindings:
            uppercase-in-0:
              consumer:
                application-id: "${spring.application.name}-uppercase"
                enable-dlq: true
                dlq-name: uppercase.dlq.v1
                dlq-partitions: 1
            aggregate-in-0:
              consumer:
                application-id: "${spring.application.name}-aggregate"


# ── Actuator ──────────────────────────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, prometheus, bindings, kafkastreamstopology
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
# ── Server ─────────────────────────────────────────────────────────────────────
server:
  port: 3000
  shutdown: graceful # also set `timeout-per-shutdown-phase`

# ── Logging ───────────────────────────────────────────────────────────────────
logging:
  level:
    com.example.aggregator: DEBUG
    org.apache.kafka.streams: INFO
    org.springframework.cloud.stream: INFO
    org.hibernate.SQL: INFO
    org.springframework.graphql: INFO
    org.springframework.security: INFO

# ── Application Properties ────────────────────────────────────────────────────
feature:
  myDemoFlag:
    enabled: false