spring:
  application:
    name: aggregator-service
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  cloud:
    function:
#      definition: aggregate
      definition: uppercase
    stream:
      bindings:
        uppercase-in-0:
          destination: "uppercase.in"
        uppercase-out-0:
          destination: "uppercase.out"

        aggregate-in-0:
          destination: topic-1
          group: kafka-aggregator
          consumer:
            use-native-decoding: true   # let Kafka Streams handle deserialization

        aggregate-in-1:
          destination: topic-2
          group: kafka-aggregator
          consumer:
            use-native-decoding: true

        aggregate-in-2:
          destination: topic-3
          group: kafka-aggregator
          consumer:
            use-native-decoding: true

        aggregate-in-3:
          destination: topic-4
          group: kafka-aggregator
          consumer:
            use-native-decoding: true

        aggregate-out-0:
          destination: aggregated-topic
          producer:
            use-native-encoding: true   # let Kafka Streams handle serialization

#      # see DefaultPollerProperties
#      poller:
#        # call the Supplier Bean every 2 second
#        fixed-delay: 2000
      kafka:
        streams:
          binder:
            applicationId: "${spring.application.name}"
            brokers: "localhost:19092"
            configuration:
              processing.guarantee: exactly_once_v2
              commit.interval.ms: 100
#              default:
#                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

# ── Actuator ──────────────────────────────────────────────────────────────────
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, prometheus, bindings, kafkastreamstopology
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
# ── Server ─────────────────────────────────────────────────────────────────────
server:
  port: 3000
  shutdown: graceful # also set `timeout-per-shutdown-phase`

# ── Logging ───────────────────────────────────────────────────────────────────
logging:
  level:
    com.example.aggregator: DEBUG
    org.apache.kafka.streams: INFO
    org.springframework.cloud.stream: INFO
    org.hibernate.SQL: INFO
    org.springframework.graphql: INFO
    org.springframework.security: INFO

# ── Application Properties ────────────────────────────────────────────────────
feature:
  postMvp:
    enabled: false