server:
  port: 3000
  shutdown: graceful # also set `timeout-per-shutdown-phase`
# ==================== logging ============================
logging:
  level:
    com.example.payments: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.security: DEBUG
# ==================== management ==========================
management:
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,prometheus,bindings,kafkastreamstopology
  prometheus:
    metrics:
      export:
        enabled: true
# ==================== spring ==============================
spring:
  application:
    name: aggregated-payments
  lifecycle:
    timeout-per-shutdown-phase: "10s"
  cloud:
    function:
#      definition: payments
      definition: uppercase
    stream:
      bindings:
        uppercase-in-0:
          destination: "uppercase.in"
        uppercase-out-0:
          destination: "uppercase.out"

        payments-in-0:
          destination: visa-payments
        payments-in-1:
          destination: mastercard-payments
        payments-in-2:
          destination: giftcard-payments
        payments-out-0:
          destination: aggregated-payments

#      # see DefaultPollerProperties
#      poller:
#        # call the Supplier Bean every 2 second
#        fixed-delay: 2000
      kafka:
        streams:
          binder:
            applicationId: "${spring.application.name}"
            brokers: "localhost:19092"
            configuration:
              processing.guarantee: exactly_once_v2
              commit.interval.ms: 100
#              default:
#                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#                value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

  # ====================security=================================

  # ====================devtools=================================
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false

# ==================== application properties  =============
feature:
  postMvp:
    enabled: false